version: 2
jobs:
 build:
   machine: true
   steps:
     - checkout

     # build the application image
     - run: docker build -t govau/cf-cli:$CIRCLE_BRANCH .

     # Test cf in the image works
     - run: docker run -it --rm govau/cf-cli:$CIRCLE_BRANCH cf --version
